### ISSUE TITLE
Write_index fails b/c of `grib_handle` issue if cfgrib version below `cfgrib-0.9.10.1`

### ISSUE THREAD

**Issue by rbanick** [gribscan/gribscan#9]
**Issue**

Any attempt to read a GRIB1 or GRIB2 file with `write_index` returns the following error:

```
gs.write_index("rtma_2011022404.grib2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/gribscan/gribscan.py", line 275, in write_index
    for record in gen:
  File "/usr/local/lib/python3.8/dist-packages/gribscan/gribscan.py", line 232, in scan_gribfile
    global_attrs = {k: m[k] for k in cfgrib.dataset.GLOBAL_ATTRIBUTES_KEYS}
  File "/usr/local/lib/python3.8/dist-packages/gribscan/gribscan.py", line 232, in <dictcomp>
    global_attrs = {k: m[k] for k in cfgrib.dataset.GLOBAL_ATTRIBUTES_KEYS}
  File "/usr/local/lib/python3.8/dist-packages/cfgrib/messages.py", line 209, in __getitem__
    return super(ComputedKeysMessage, self).__getitem__(item)
  File "/usr/local/lib/python3.8/dist-packages/cfgrib/messages.py", line 161, in __getitem__
    return self.message_get(item)
  File "/usr/local/lib/python3.8/dist-packages/cfgrib/messages.py", line 123, in message_get
    values = eccodes.codes_get_array(self.codes_id, item, key_type)
  File "/usr/local/lib/python3.8/dist-packages/cfgrib/bindings.py", line 366, in codes_get_array
    key_type = codes_get_native_type(handle, key)
  File "/usr/local/lib/python3.8/dist-packages/cfgrib/bindings.py", line 359, in codes_get_native_type
    _codes_get_native_type(handle, key.encode(ENC), grib_type)
  File "/usr/local/lib/python3.8/dist-packages/cfgrib/bindings.py", line 163, in wrapper
    code = func(*args)
TypeError: initializer for ctype 'grib_handle *' must be a cdata pointer, not int
```

**Inputs**

GRIB1 files from ERA5 Land (temp and precipitation) and GRIB2 files from RTMA (https://www.nco.ncep.noaa.gov/pmb/products/rtma/)

These are saved to [here](https://www.dropbox.com/sh/p90v5a8s7fm1ul5/AACDagE5y6hUs1J3nRrkMGhka?dl=0) for reference

**Setup**

Ubuntu `20.04.3 LTS`
Python `3.8.3`
Eccodes `2.26`
cfgrib `'0.9.8.5'`
Latest released version of gribscan (installed via python -m pip install gribscan)

**Comment by rbanick** [comment]
Aaaand immediately after posting this I found that an upgrade to `cfgrib` to the latest version (`cfgrib-0.9.10.1`) fixes the issue. Embarrassing but a useful finding for the docs.

**Comment by d70-t** [comment]
😬 that's very unfortunate. I stumbled across that before and actually commited this dependency to setup.py a few days ago, but forgot to merge it (see #10).

**Comment by d70-t** [comment]
Thanks for reporting 🚀! I hope it should be fixed now.
